### ISSUE TITLE
Debug tool - Jump to the pid

### ISSUE THREAD

**Issue by Polar-Phoenix** [barabulkit/PalladaProject#3]
In order to make playtests simple debug tool is required.
It should be simple modal window\secret button\console command which allow to jump to a specific pid, ignoring triggers, progress of player, etc.

**Comment by barabulkit** [comment]
added cheats console
press ~ or ` to open
/add <trigger> to add trigger to triggers list
/list to list all active triggers
/goto <pid_num> to go to passage with this pid

**Comment by barabulkit** [comment]
press Esc to close console
